from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field


class LLMStatusResponse(BaseModel):
    provider: str = Field("ollama", examples=["ollama"])
    endpoint: str = Field("http://127.0.0.1:11434", examples=["http://127.0.0.1:11434"])
    model: str = Field(..., examples=["llama3.2:3b"])
    available: bool = Field(..., examples=[True, False])
    status: str = Field(..., examples=["available", "llm_unavailable", "model_not_found"])
    base_url: str = Field("http://127.0.0.1:11434", examples=["http://127.0.0.1:11434"])
    installed_models: List[str] = Field(default_factory=list)
    message: Optional[str] = Field(None, examples=["Local model 'llama3.2:3b' is ready for inference."])


class LLMGenerateRequest(BaseModel):
    prompt: str = Field(..., min_length=1)
    system: Optional[str] = Field(None)
    model: Optional[str] = Field(None)
    temperature: Optional[float] = Field(None, ge=0.0, le=1.0)
    top_p: Optional[float] = Field(None, ge=0.0, le=1.0)
    num_ctx: Optional[int] = Field(None, ge=512, le=32768)
    stream: bool = Field(False)


class LLMGenerateResponse(BaseModel):
    success: bool = Field(True)
    status: str = Field("success", examples=["success", "llm_unavailable", "model_not_found", "generation_timeout", "generation_error"])
    model: str = Field(..., examples=["llama3.2:3b"])
    response: str = Field(..., description="Raw text output generated by local LLM")
    total_duration_ms: float = Field(0.0)
    prompt_eval_count: Optional[int] = Field(None)
    eval_count: Optional[int] = Field(None)
    message: Optional[str] = Field(None)
